<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli') { http_response_code(404); exit; }
require_once __DIR__.'/../api/contract-model.php';
require_once __DIR__.'/../api/contract-pdf.php';
require_once __DIR__.'/../api/contract-review.php';
function packageAssert(bool $ok,string $message): void { if(!$ok) throw new RuntimeException($message); }
$site=contractSampleContract('website'); $app=contractSampleContract('webapp'); $shop=contractSampleContract('ecommerce');
packageAssert(count($site['package']['documents'])===4,'Site needs specification, rights, privacy and hosting');
packageAssert(count($app['package']['documents'])===5,'Application needs a real DPA');
packageAssert(count($shop['package']['documents'])===6,'Protected customer needs notices and withdrawal form');
packageAssert(contractPackageMissing($site['facts'])===[],'Complete fictional package facts');
$purchase=$site; $purchase['facts']['publicationDestination']='agency_purchase';
$purchase['facts']['productionDomain']='example.test';
packageAssert(contractFactsMissing($purchase['facts'])!==[],'Purchase requires actual agreed domain terms');
foreach(['domainRegistrant','domainPurchaseTerms','domainAvailabilityTerms','domainRenewalTerms','domainHandoverTerms'] as $key) $purchase['facts'][$key]='Fictional agreed terms for '.$key;
packageAssert(contractFactsMissing($purchase['facts'])===[],'Purchase does not require client hosting details');
$docs=contractPackageBuild($purchase)['documents'];
packageAssert(in_array('hosting',array_column($docs,'id'),true)&&in_array('domain_purchase',array_column($docs,'id'),true),'Purchase includes domain and agency hosting appendices');
packageAssert(contractPublicationFieldApplicable('productionDomain',$purchase['facts']),'Purchase needs target domain');
packageAssert(!contractPublicationFieldApplicable('productionHosting',$purchase['facts']),'Purchase excludes customer server questions');
packageAssert(in_array('domainRenewalTerms',contractRequiredReview([],$purchase['facts']),true),'Domain renewal terms need manual review');
$purchase['facts']['hostingFee']=''; packageAssert(contractFactsMissing($purchase['facts'])!==[],'Purchase still requires hosting price');
$bad=$site['facts']; $bad['hostingFee']=''; packageAssert(contractPackageMissing($bad)!==[],'Agency hosting must not bypass price and duration');
$bad=$site['facts']; $bad['rightsInventory']='[]'; packageAssert(contractPackageMissing($bad)!==[],'Empty inventory cannot pass');
$bad=$app['facts']; $bad['processingSubprocessors']='[{"name":"unknown"}]'; packageAssert(contractPackageMissing($bad)!==[],'Subprocessors require service and location');
$handoff=$site; $handoff['facts']['publicationDestination']='client_handoff';
packageAssert(!in_array('hosting',array_column(contractPackageBuild($handoff)['documents'],'id'),true),'Client handoff excludes agency hosting');
$site['pdfBase64']=base64_encode(contractPdf($site)); $site['package']['pdfSha256']=hash('sha256',base64_decode($site['pdfBase64']));
packageAssert(contractPackageIntegrity($site),'Generated bytes and content match');
packageAssert(!contractPackageApproved($site),'Completeness does not imply legal review');
$site['package']['legalReview']=['packageHash'=>$site['package']['hash'],'pdfSha256'=>$site['package']['pdfSha256']];
packageAssert(contractPackageApproved($site),'Exact reviewed package');
$rules=contractPackageExecutionInstructions(['contract'=>$site],['sourceContractVersion'=>1,'contractSignedPackageHash'=>$site['package']['hash']]);
packageAssert(str_contains(implode(' ',$rules),$site['facts']['acceptanceCriteria']),'Agents receive contractual acceptance criteria');
packageAssert(!str_contains(implode(' ',$rules),'studio@example.test'),'Full party identity and contact are not sent as legal context');
try { contractPackageExecutionInstructions(['contract'=>$site],['sourceContractVersion'=>1]); throw new LogicException('Unconfirmed package reached agents'); } catch(RuntimeException $expected) {}
$changed=$site; $changed['scope'].=' altered'; packageAssert(!contractPackageApproved($changed),'Changing scope invalidates review');
$changed=$site; $changed['facts']['clientType']='protected'; packageAssert(!contractPackageApproved($changed),'Changing status invalidates review');
$changed=$site; $changed['package']['documents'][0]['sections']['Kryteria odbioru']='tampered'; packageAssert(!contractPackageApproved($changed),'Changing stored annex invalidates review');
$changed=$site; $changed['pdfBase64']=base64_encode('other PDF'); packageAssert(!contractPackageApproved($changed),'Changing PDF bytes invalidates review');
$changed=$site; $changed['version']=2; packageAssert(!contractPackageApproved($changed),'Review cannot be copied to a new version');
// Withdrawal deadline ending on Sunday / holiday extends through the next working day.
$zone=new DateTimeZone('Europe/Warsaw'); $at=static fn($date)=>(new DateTimeImmutable($date.' 12:00',$zone))->getTimestamp();
packageAssert(contractPackageEarliestStart($at('2026-10-04'),$at('2026-10-04'),14)==='2026-10-20','Sunday extends to Monday, start Tuesday');
packageAssert(contractPackageEarliestStart($at('2026-12-10'),$at('2026-12-10'),14)==='2026-12-29','Christmas holidays and weekend extend deadline');
packageAssert(contractPackageEarliestStart($at('2026-10-01'),$at('2026-10-05'),30)==='2026-11-05','Conservative start uses latest recorded receipt or signature evidence');
echo "Contract package checks passed: applicability, actual annexes, completeness, tamper detection, review binding, withdrawal dates.\n";
