import { spawn } from 'node:child_process';
import { createServer } from 'node:http';
import { mkdtemp, readFile, rm, realpath, mkdir, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve, sep } from 'node:path';
import { strict as assert } from 'node:assert';
import { previewPasswordHash, previewPasswordMatches } from '../services/vps-control/auth.mjs';

const root = await mkdtemp(join(tmpdir(), 'grzywniak-vps-test-'));
const port = 31000 + Math.floor(Math.random() * 1000);
const appPort = port + 1200;
const token = 'test-token-' + 'x'.repeat(40);
const projectId = 'a'.repeat(32);
const password = 'preview-test-password-123456';
const salt = '00112233445566778899aabbccddeeff';
  assert.deepEqual(await readFile(resolve('services/vps-control/feedback.js')), await readFile(resolve('templates/web-vite/public/grzywniak-feedback.js')), 'Skrypt dołączany przez bramę musi być zsynchronizowany z szablonem projektu.');
const generatedAuth = { previewAuthUser: 'client', ...previewPasswordHash(password, salt) };
assert.equal(previewPasswordMatches(generatedAuth, `Basic ${Buffer.from(`client:${password}`).toString('base64')}`), true, 'Wygenerowane dane muszą być zapisane w polach odczytywanych przez bramkę logowania.');
assert.equal(previewPasswordMatches(generatedAuth, `Basic ${Buffer.from(`wrong:${password}`).toString('base64')}`), false);
await mkdir(join(root, 'state'), { recursive: true });
const deploymentId = 'test-preview-deployment';
await writeFile(join(root, 'state', 'state.json'), JSON.stringify({ projects: { [`${projectId}:preview`]: { projectId, kind: 'preview', hostname: 'p-aaaaaaaaaaaa.grzywniak.pl', repository: 'https://github.com/Grzywniak/test', current: deploymentId, previous: null, ...generatedAuth, feedbackToken: 'b'.repeat(48), feedbackUrl: 'https://not-api.example/project-feedback.php?project=x' } }, deployments: { [deploymentId]: { projectId, kind: 'preview', container: '127.0.0.1', appPort, imageDigest: `sha256:${'c'.repeat(64)}` } } }));
const app = createServer((request, response) => {
  if (request.url === '/health') { response.writeHead(200, { 'content-type': 'text/plain' }); return response.end('ok'); }
  if (request.url === '/asset.js') { response.writeHead(200, { 'content-type': 'text/javascript' }); return response.end('window.assetLoaded=true'); }
  response.writeHead(200, { 'content-type': 'text/html; charset=utf-8' }); response.end('<!doctype html><html><body><main>Preview app</main></body></html>');
});
await new Promise((resolve) => app.listen(appPort, '127.0.0.1', resolve));
const server = spawn(process.execPath, [resolve('services/vps-control/server.mjs')], { cwd: resolve('.'), env: { ...process.env, VPS_DATA_DIR: join(root, 'state'), TRAEFIK_DYNAMIC_DIR: join(root, 'dynamic'), VPS_LISTEN_PORT: String(port), VPS_CONTROL_TOKEN: token, VPS_CONTROL_HOST: 'control.grzywniak.pl' }, stdio: 'ignore' });
try {
  let ready = false;
  for (let attempt = 0; attempt < 30; attempt++) {
    try { const response = await fetch(`http://127.0.0.1:${port}/missing`); if (response.status === 401) { ready = true; break; } } catch {}
    await new Promise((done) => setTimeout(done, 100));
  }
  assert(ready, 'Usługa VPS nie wystartowała.');
  const unauthorized = await fetch(`http://127.0.0.1:${port}/v1/projects`, { method: 'POST' });
  assert.equal(unauthorized.status, 401);
  const invalid = await fetch(`http://127.0.0.1:${port}/v1/projects`, { method: 'POST', headers: { authorization: `Bearer ${token}`, 'content-type': 'application/json', 'idempotency-key': 'bad' }, body: JSON.stringify({ projectId: 'bad', hostname: 'bad', kind: 'preview', repository: 'https://github.com/Other/repo' }) });
  assert.equal(invalid.status, 400);
  const controlRoute = await readFile(join(root, 'dynamic', 'vps-control.yml'), 'utf8');
  assert(controlRoute.includes('Host(`control.grzywniak.pl`)'));
  const route = await readFile(join(root, 'dynamic', 'gw-aaaaaaaaaaaaaaaa-preview.yml'), 'utf8');
  assert(route.includes('forwardAuth:'));
  assert(route.includes('/internal/preview-auth?key=' + encodeURIComponent(token)));
  assert(route.includes('http://vps-control:3010'), 'Podglądy powinny przechodzić przez bramę nakładki uwag.');
  const headers = { 'x-forwarded-host': 'p-aaaaaaaaaaaa.grzywniak.pl' };
  const blocked = await fetch(`http://127.0.0.1:${port}/internal/preview-auth?key=${encodeURIComponent(token)}`, { headers });
  assert.equal(blocked.status, 401, 'Podgląd bez hasła powinien zostać zablokowany.');
  const allowed = await fetch(`http://127.0.0.1:${port}/internal/preview-auth?key=${encodeURIComponent(token)}`, { headers: { ...headers, authorization: `Basic ${Buffer.from(`client:${password}`).toString('base64')}` } });
  assert.equal(allowed.status, 200, 'Poprawne hasło powinno odblokować podgląd.');
  const config = await fetch(`http://127.0.0.1:${port}/internal/feedback-config`, { headers: { ...headers, authorization: `Basic ${Buffer.from(`client:${password}`).toString('base64')}` } });
  assert.equal(config.status, 200);
  const feedbackConfig = await config.json();
  assert.equal(feedbackConfig.feedbackToken, 'b'.repeat(48));
  assert.equal(feedbackConfig.canAccept, false);
  const appHeaders = { host: 'p-aaaaaaaaaaaa.grzywniak.pl', 'x-forwarded-host': 'p-aaaaaaaaaaaa.grzywniak.pl', authorization: `Basic ${Buffer.from(`client:${password}`).toString('base64')}` };
  const preview = await fetch(`http://127.0.0.1:${port}/`, { headers: appHeaders });
  const html = await preview.text();
  assert.equal(preview.status, 200);
  assert.match(html, /<script src="\/grzywniak-html2canvas\.js" defer><\/script><script src="\/grzywniak-feedback\.js" defer><\/script><\/body>/, 'Bramka powinna dołączyć renderer obrazu przed nakładką uwag.');
  const canvasLibrary = await fetch(`http://127.0.0.1:${port}/grzywniak-html2canvas.js`, { headers: appHeaders });
  assert.equal(canvasLibrary.status, 200);
  assert.match(canvasLibrary.headers.get('content-type') || '', /javascript/);
  assert.match(await canvasLibrary.text(), /html2canvas/);
  const script = await fetch(`http://127.0.0.1:${port}/grzywniak-feedback.js`, { headers: appHeaders });
  assert.equal(script.status, 200);
  const scriptText = await script.text();
  assert.match(scriptText, /gw-feedback-launcher/);
  assert.match(scriptText, /Zaznacz kolejny obszar/);
  assert.match(scriptText, /annotation: \{ areas: annotations \}/);
  assert.match(scriptText, /window\.html2canvas\(document\.documentElement/);
  assert.match(scriptText, /screenshot: image/);
  assert.match(scriptText, /gw-accept-button/);
  assert.match(scriptText, /gw-closed \.gw-primary\{display:none\}/, 'Po zamknięciu listy ukryj nieaktywny przycisk wysyłki uwagi.');
  assert.match(scriptText, /\.gw-primary\{[^}]*cursor:pointer!important\}/, "The feedback submit button keeps a clear clickable cursor.");
  assert.match(scriptText, /button:disabled\{opacity:\.55;cursor:default!important\}/, "Disabled feedback buttons do not show a loading cursor.");
  assert.doesNotMatch(scriptText, /cursor:\s*wait/, 'Panel uwag nie pokazuje obracającego się kursora oczekiwania.');
  assert.match(scriptText, /aria-busy/, "Submission exposes a clear busy state.");
  assert.match(scriptText, /submit\.disabled = Boolean/, "A closed feedback list stays locked when a pending request completes.");
  assert.match(scriptText, /action: \"accept\"/);
  assert.match(scriptText, /config\.previewAccepted/);
  assert.match(scriptText, /toDataURL\("image\/jpeg"/);
  assert.match(scriptText, /node\.removeAttribute\("value"\)/, 'Zapisany podgląd nie może przenosić wpisanych wartości pól formularza.');
  assert.match(scriptText, /Notatka do tego obszaru/);
  assert.match(scriptText, /annotation\.note = note\.value/);
  assert.match(scriptText, /context\.x \* annotation\.viewport\.width \* scale/);
  assert.match(scriptText, /context: \{ x: left \/ innerWidth, y: top \/ innerHeight, width: width \/ innerWidth, height: height \/ innerHeight \}/, 'Zrzut powinien zawierać zaznaczenie i margines strony wokół niego.');
  assert.match(scriptText, /location\.origin\}\$\{location\.pathname\}\$\{location\.hash\}/, 'Ukryta informacja o podstronie powinna zachować ścieżkę i trasę SPA, bez query stringa.');
  assert.match(scriptText, /gw-thumb-selection/);
  assert.match(scriptText, /gw-feedback-viewer/);
  assert.match(scriptText, /Powiększ zaznaczony obszar/);
  assert.match(scriptText, /thumbWidth = Math\.min\(320, areasEl\.clientWidth, 110 \* ratio\)/);
  assert.doesNotMatch(scriptText, /annotation\.element\.tag/, 'Etykieta miniatury nie powinna ujawniać technicznych nazw tagów HTML.');
  assert.doesNotMatch(scriptText, /sandbox/, 'Miniatury muszą dziedziczyć pochodzenie podglądu, aby style nie były blokowane przez CORS.');
  assert.match(scriptText, /ignoreElements: \(node\) => \/\^gw-feedback-\//, 'Nakładka zgłoszeniowa musi być wykluczona ze zrzutu obrazu.');
  assert.match(scriptText, /feedback-submit/);
  assert.match(scriptText, /result\.reference/, 'Błąd zapisu powinien pokazać identyfikator do odnalezienia wpisu w logu PHP.');
  assert.doesNotMatch(scriptText, /endpoint\.origin/, 'Wysyłka zgłoszenia powinna być same-origin, bez przeglądarkowego CORS do API.');
  const asset = await fetch(`http://127.0.0.1:${port}/asset.js`, { headers: appHeaders });
  assert.equal(await asset.text(), 'window.assetLoaded=true', 'Pozostałe zasoby powinny być przekazywane do aplikacji bez zmian.');
  const blockedPreview = await fetch(`http://127.0.0.1:${port}/`, { headers: { host: 'p-aaaaaaaaaaaa.grzywniak.pl', 'x-forwarded-host': 'p-aaaaaaaaaaaa.grzywniak.pl' } });
  assert.equal(blockedPreview.status, 401, 'Bramka musi wymagać hasła przed pokazaniem strony i nakładki.');
  const feedbackSubmission = await fetch(`http://127.0.0.1:${port}/.well-known/grzywniak/feedback-submit`, { method: 'POST', headers: { ...appHeaders, 'content-type': 'application/json' }, body: JSON.stringify({ message: 'Sprawdź dwa zaznaczone miejsca.', page_url: 'https://p-aaaaaaaaaaaa.grzywniak.pl/', annotation: { areas: [] } }) });
  assert.equal(feedbackSubmission.status, 502, 'Wysyłka uwag powinna być dostępna pod ścieżką same-origin.');
  assert.match((await feedbackSubmission.json()).message, /zaufanego API/);
  console.log('VPS control auth, feedback configuration and preview overlay checks OK');
} finally {
  server.kill();
  app.close();
  const target = await realpath(root);
  const parent = await realpath(tmpdir());
  if (!target.startsWith(parent + sep)) throw new Error('Odmowa usunięcia katalogu poza temp.');
  await rm(target, { recursive: true, force: true });
}
