<?php
declare(strict_types=1);
require_once __DIR__.'/bootstrap.php';
require_once __DIR__.'/admin-shell.php';
$user=(string)(getenv('ADMIN_USERNAME')?:''); $password=(string)(getenv('ADMIN_PASSWORD')?:'');
if($user===''||$password===''||!hash_equals($user,(string)($_SERVER['PHP_AUTH_USER']??''))||!hash_equals($password,(string)($_SERVER['PHP_AUTH_PW']??''))) { header('WWW-Authenticate: Basic realm="Grzywniak Discovery"'); http_response_code(401); exit('Authentication required.'); }
header('Content-Type: text/html; charset=utf-8'); header('Cache-Control: no-store');
$sessions=array_values(array_filter(allSessions(),static fn($item)=>is_array($item)&&!empty($item['messages'])));
$briefs=count(array_filter($sessions,static fn($item)=>($item['status']??'')==='COMPLETED'));
$cards=[
    ['Panel briefów','Rozmowy klientów, analizy, oferty i umowy.','/api/admin.php','Otwórz rozmowy'],
    ['Centrum projektów','Mapa spraw od briefu do budowy i wdrożenia.','/api/project-portfolio.php','Otwórz projekty'],
    ['Ustawienia','GitHub, Cloudflare, VPS, agenci i limity.','/api/project-settings.php','Otwórz konfigurację'],
];
?><!doctype html><html lang="pl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Panel admina · Grzywniak</title><?=adminShellStyles()?><style>:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 78% -10%,#182b56,transparent 36%),#080d18;color:#eff4ff;font:15px/1.5 system-ui,sans-serif}main{max-width:1150px;margin:auto;padding:48px 23px 80px}.eyebrow{color:#8ea5fa;text-transform:uppercase;letter-spacing:.15em;font-size:11px;font-weight:750}h1{font-size:clamp(33px,5vw,48px);letter-spacing:-.045em;margin:7px 0}.lead{color:#a9b8d2;max-width:620px;margin:0}.stats{display:flex;gap:13px;flex-wrap:wrap;margin:29px 0}.stat{border:1px solid #344568;background:#121d30;border-radius:13px;padding:14px 18px;min-width:160px}.stat b{display:block;font-size:24px}.stat span{font-size:12px;color:#a9b8d2}.cards{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:17px;margin-top:31px}.card{display:flex;flex-direction:column;min-height:240px;padding:23px;border:1px solid #34435e;border-radius:18px;background:linear-gradient(145deg,#17243b,#101827);text-decoration:none;color:inherit;transition:transform .18s,border-color .18s}.card:hover,.card:focus-visible{transform:translateY(-3px);border-color:#8ba5f9;outline:none}.card .num{color:#91a5e8;font-size:11px;font-weight:800;letter-spacing:.14em}.card h2{font-size:21px;letter-spacing:-.025em;margin:18px 0 8px}.card p{color:#a9bad4;margin:0}.card strong{margin-top:auto;padding-top:20px;color:#b8c8ff;font-size:13px}@media(max-width:760px){main{padding:32px 15px}.cards{grid-template-columns:1fr}.card{min-height:185px}}</style></head><body><?=adminShellHeader('home')?><main><span class="eyebrow">Przegląd</span><h1>Panel admina</h1><p class="lead">Wybierz obszar pracy. Wspólny nagłówek pozwala przełączać się między rozmowami, projektami i ustawieniami z każdej strony.</p><div class="stats"><div class="stat"><b><?=count($sessions)?></b><span>rozmów klientów</span></div><div class="stat"><b><?=$briefs?></b><span>przekazanych briefów</span></div></div><div class="cards"><?php foreach($cards as $index=>[$title,$description,$href,$action]):?><a class="card" href="<?=htmlspecialchars($href,ENT_QUOTES)?>"><span class="num">0<?=$index+1?></span><h2><?=htmlspecialchars($title,ENT_QUOTES)?></h2><p><?=htmlspecialchars($description,ENT_QUOTES)?></p><strong><?=htmlspecialchars($action,ENT_QUOTES)?> →</strong></a><?php endforeach?></div></main></body></html>
