<?php
declare(strict_types=1);

/** Editable examples, not statements about the agency's actual services. */
function contractFieldSuggestions(string $key): array {
    $fill=static fn(string $name)=>'[DO UZUPEŁNIENIA: '.$name.']';
    $delivery='Materiały są przekazywane przez sekcję materiałów projektu lub uzgodniony bezpieczny kanał. Wykonawca sprawdza kompletność i zgłasza braki. Przy opóźnieniu strony zapisują brakujące materiały i wpływ na prace oraz uzgadniają nowy harmonogram; termin nie przesuwa się automatycznie bez wykazania wpływu.';
    $data=[
        'cooperationTerms'=>[
            'Klient dostarcza materiały'=>'Klient dostarcza teksty, logo oraz zdjęcia, do których ma prawo użycia, do '.$fill('termin dostarczenia materiałów').'. '.$delivery,
            'Teksty po naszej stronie'=>'Klient dostarcza logo, zdjęcia i informacje merytoryczne do '.$fill('termin').'. Wykonawca przygotowuje teksty w zakresie oferty; klient sprawdza ich zgodność z działalnością przed publikacją. '.$delivery,
            'Materiały przygotowuje zespół'=>'Wykonawca przygotowuje materiały wymienione w zakresie oferty: '.$fill('teksty, grafiki, zdjęcia i ich źródła').'. Klient dostarcza informacje merytoryczne i zatwierdza treść. Zakup zdjęć lub licencji wymaga uprzedniego uzgodnienia kosztu. Terminy: '.$fill('termin informacji klienta i przygotowania materiałów').'. '.$delivery,
        ],
        'legalStatusBasis'=>[
            'Firma — do weryfikacji'=>'Klient działa jako '.$fill('forma prawna, wpis do rejestru i reprezentacja').'. Cel zakupu: '.$fill('związek projektu z działalnością oraz zawodowy charakter umowy, jeśli klient jest osobą fizyczną').'. Status klienta ustalono na podstawie '.$fill('sprawdzone dokumenty i ustalenia').'.',
            'Osoba prywatna'=>'Klient jest osobą fizyczną, a projekt zamawia w celu '.$fill('cel niezwiązany bezpośrednio z działalnością gospodarczą lub zawodową').'. Podstawa ustalenia: '.$fill('fakty i oświadczenia klienta').'.',
        ],
        'acceptanceCriteria'=>['Strona internetowa'=>'Wersja zawiera widoki i funkcje z zaakceptowanej oferty: '.$fill('konkretne widoki i scenariusze').'. Sprawdzamy działanie kontaktu, linków i nawigacji, czytelność na telefonie i komputerze oraz zgodność treści z zatwierdzonymi materiałami. Środowiska i wyniki wymaganych testów: '.$fill('przeglądarki, rozmiary ekranów, kryteria dostępności i pozostałe testy').'.', 'Aplikacja webowa'=>'Odbiór obejmuje scenariusze '.$fill('operacje użytkowników i oczekiwane wyniki').', role i uprawnienia '.$fill('role').', integracje '.$fill('integracje i kryteria').'. Testy oraz wymagane wyniki: '.$fill('testy funkcjonalne, bezpieczeństwa, dostępności i wydajności').'.'],
        'privacyRecipients'=>['Wykaz rzeczywistych dostawców'=>'Odbiorcy danych umownych: '.$fill('dostawcy poczty, hostingu, księgowości oraz inne podmioty i ich role').'. Lokalizacje: '.$fill('kraje przechowywania i dostępu').'. Transfery poza EOG i ich zabezpieczenia albo potwierdzony brak: '.$fill('rzeczywiste transfery i podstawa').'. Dane nie są udostępniane narzędziom AI bez uprzedniego sprawdzenia podstawy i warunków.'],
        'privacyRetention'=>['Przechowywanie według celu'=>'Dane umowne przechowujemy przez '.$fill('okres realizacji, rozliczeń i dochodzenia roszczeń z uzasadnieniem').'. Dokumenty rozliczeniowe: '.$fill('właściwy okres ustawowy i sposób jego liczenia').'. Źródło danych reprezentantów: '.$fill('klient, reprezentant lub wskazany rejestr').'. Po ustaniu podstaw dane usuwamy lub anonimizujemy.'],
        'hostingFee'=>['Rozliczenie miesięczne'=>'Hosting: '.$fill('kwota brutto').' miesięcznie. Płatnik: '.$fill('klient lub inny uzgodniony płatnik').'. Zakres: '.$fill('zasoby, obsługa i limity').'. Dodatkowe koszty: '.$fill('koszty lub potwierdzony brak').'. Usługi poza zakresem wymagają osobnej zgody i wyceny.', 'Rozliczenie roczne'=>'Hosting: '.$fill('kwota brutto').' za rok. Płatnik: '.$fill('płatnik').'. Zakres i limity: '.$fill('zakres').'. Cena odnowienia i zasady jej zmiany: '.$fill('ustalenia').'. Dodatkowe koszty: '.$fill('koszty lub potwierdzony brak').'.'],
        'hostingPeriod'=>['Czas nieokreślony'=>'Hosting na czas nieokreślony, z okresem wypowiedzenia '.$fill('okres i sposób wypowiedzenia').'. O planowanej zmianie ceny informujemy '.$fill('termin powiadomienia').' wcześniej; warunki wejścia zmiany w życie i możliwość zakończenia usługi: '.$fill('ustalenia').'.', 'Okres roczny'=>'Hosting przez 12 miesięcy od '.$fill('data startu').'. Odnowienie: '.$fill('zasady zgody i płatności').'. Wypowiedzenie i rozliczenie niewykorzystanego okresu: '.$fill('zasady').'. Zmianę ceny zgłaszamy '.$fill('termin powiadomienia').' wcześniej.'],
        'hostingBackup'=>['Plan kopii zapasowych'=>'Zakres kopii: '.$fill('pliki, baza, konfiguracja').'. Częstotliwość: '.$fill('częstotliwość').'; retencja: '.$fill('okres').'; miejsce przechowania: '.$fill('lokalizacja i dostawca').'. Test odtworzenia: '.$fill('częstotliwość i sposób').'. Uzgodniony czas odtworzenia i dopuszczalna utrata danych: '.$fill('rzeczywiste możliwości i limity').'. Odpowiedzialny: '.$fill('osoba lub podmiot').'.'],
        'hostingExit'=>['Eksport i zakończenie'=>'Po zakończeniu hostingu przekazujemy kod i dane objęte umową w formacie '.$fill('formaty i zakres').' w terminie '.$fill('termin').' bezpiecznym kanałem. Koszt eksportu i migracji: '.$fill('koszt lub potwierdzony brak').'. Dane aktywne usuwamy po '.$fill('termin').', a kopie po '.$fill('okres rotacji').', z wyjątkiem danych wymaganych prawem.'],
        'hostingDns'=>['Hosting u nas'=>'Operator infrastruktury: '.$fill('rzeczywisty operator').'; lokalizacja danych i dostępu: '.$fill('lokalizacja').'. Wykonawca obsługuje routing, DNS i TLS w zakresie '.$fill('domeny, uprawnienia i granice obsługi').'. Odnowienie domeny: '.$fill('odpowiedzialny').'. Awarie zgłaszane są przez '.$fill('kontakt, godziny i czasy reakcji').'.'],
        'domainRegistrant'=>['Domena na klienta'=>'Domena jest rejestrowana na zamawiającego wskazanego w umowie. Wykonawca działa na jego udokumentowane upoważnienie obejmujące '.$fill('zakres rejestracji i obsługi').'. Dane abonenta oraz kontakt do potwierdzeń klient sprawdza przed rejestracją.'],
        'domainPurchaseTerms'=>['Zakup z limitem kosztu'=>'Klient pokrywa koszt rejestracji do '.$fill('limit brutto').' za '.$fill('okres rejestracji').'. Przed zakupem administrator potwierdza cenę i zgodność z upoważnieniem. Przekroczenie limitu wymaga dodatkowej zgody klienta. Sposób rozliczenia: '.$fill('zaliczka, zwrot kosztu lub faktura').'.'],
        'domainAvailabilityTerms'=>['Sprawdzenie przed zakupem'=>'Przed zakupem sprawdzamy dostępność nazwy i warunki rejestratora. Wskazanie nazwy w briefie nie oznacza jej rezerwacji. Jeśli jest zajęta lub cena przekracza ustalony limit, przedstawiamy alternatywy; klient zatwierdza wybraną nazwę przed zakupem.'],
        'domainRenewalTerms'=>['Odnowienie po potwierdzeniu'=>'Za przypomnienie odpowiada '.$fill('osoba lub podmiot').'; informację przekazuje '.$fill('liczba dni i kanał').' przed wygaśnięciem. Koszt kolejnego okresu: '.$fill('cena brutto lub sposób ustalenia').'. Zmiana ceny i zlecenie odnowienia wymagają uzgodnionej zgody. Brak płatności może skutkować wygaśnięciem domeny i niedostępnością strony; sposób uprzedzenia klienta: '.$fill('procedura').'.'],
        'domainHandoverTerms'=>['Kontrola domeny dla klienta'=>'Klient otrzymuje kontrolę konta lub dostęp niezbędny do obsługi domeny przez '.$fill('bezpieczny kanał').' w terminie '.$fill('termin').'. Zakończenie obsługi i przekazanie DNS: '.$fill('procedura i koszt odrębnych prac').'. Dla domen .pl wydanie AuthInfo nie zależy od opłat za inne prace. Hasła i kody przekazujemy poza treścią umowy.'],
        'consumerTechnical'=>['Strona — parametry i reklamacje'=>'Wymagania korzystania: '.$fill('urządzenia, przeglądarki, dostęp do internetu').'. Funkcjonalność i ograniczenia: '.$fill('uzgodnione funkcje i ograniczenia').'. Interoperacyjność, zabezpieczenia i aktualizacje: '.$fill('rzeczywiste parametry i okres aktualizacji').'. Reklamacje: '.$fill('adres, kanał, procedura i właściwe terminy').'. Ustalenia nie ograniczają ustawowych praw klienta.'],
        'processingPurpose'=>['Hosting i utrzymanie aplikacji'=>'Przedmiot: hosting i utrzymanie '.$fill('aplikacja i zakres').'. Cel: realizacja udokumentowanych poleceń administratora. Operacje: '.$fill('przechowywanie, odczyt, kopie, usuwanie i inne faktyczne operacje').'. Dane nie służą szkoleniu AI ani własnym celom wykonawcy.'],
        'processingDuration'=>['Na czas usługi'=>'Przetwarzanie trwa przez '.$fill('okres i zdarzenie początku').' do zakończenia '.$fill('usługa').'. Po zakończeniu stosuje się uzgodniony termin zwrotu lub usunięcia, obejmujący również kopie.'],
        'processingCategories'=>['Dane kontaktowe użytkowników'=>'Rodzaje danych: '.$fill('np. imię, e-mail, telefon — tylko faktycznie przetwarzane').'. Kategorie osób: '.$fill('np. użytkownicy lub osoby wysyłające zapytania').'. Dane szczególnych kategorii oraz inne dane wrażliwe: '.$fill('potwierdzony brak albo dokładny zakres i warunki').'.'],
        'processingLocations'=>['Wykaz lokalizacji'=>'Dane są przechowywane i dostępne w '.$fill('rzeczywiste kraje, operatorzy i lokalizacje wsparcia').'. Transfery poza EOG: '.$fill('potwierdzony brak albo podstawa i konkretne zabezpieczenia').'. Zmiana lokalizacji wymaga procedury uzgodnionej z administratorem.'],
        'processingSecurity'=>['Opis wdrożonych zabezpieczeń'=>'Rzeczywiście wdrożone środki: '.$fill('kontrola dostępu i role, MFA, TLS, szyfrowanie danych, kopie, aktualizacje, rejestry i testy — z parametrami').'. Osoby upoważnione zachowują poufność. Przeglądy: '.$fill('częstotliwość i odpowiedzialny').'. Nie deklarujemy zabezpieczeń, które nie działają w środowisku projektu.'],
        'processingReturn'=>['Zwrot lub usunięcie na wybór klienta'=>'Po zakończeniu administrator wybiera zwrot lub usunięcie danych. Termin i format zwrotu: '.$fill('termin, format i bezpieczny kanał').'. Usunięcie danych i kopii: '.$fill('terminy i sposób potwierdzenia').'. Przechowanie wymagane prawem: '.$fill('podstawa i zakres albo potwierdzony brak').'.'],
        'processingIncident'=>['Zgłaszanie naruszeń'=>'Kontakt administratora do naruszeń: '.$fill('kanał i osoba').'. Wykonawca zgłasza naruszenie bez zbędnej zwłoki, maksymalnie w ciągu '.$fill('uzgodniony czas od stwierdzenia').' oraz przekazuje znane okoliczności, skutki i podjęte działania. Kolejne informacje uzupełnia po ich ustaleniu.'],
    ];
    if($key==='rightsInventory') return ['Składnik własny — uzupełnij dane'=>json_encode([['name'=>$fill('nazwa utworu'),'origin'=>'own','author'=>$fill('rzeczywisty autor'),'license'=>$fill('zakres praw zgodny z umową'),'rightsBasis'=>$fill('własne autorstwo lub dokument nabycia praw'),'maintenanceRights'=>$fill('prawa utrzymania i modyfikacji przez inny zespół')]],JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR)];
    if($key==='processingSubprocessors') return ['Dostawca — uzupełnij dane'=>json_encode([['name'=>$fill('rzeczywisty dostawca'),'service'=>$fill('usługa i zakres dostępu'),'location'=>$fill('kraje przechowywania i dostępu')]],JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR)];
    return $data[$key]??[];
}
