<?php
declare(strict_types=1);
require_once __DIR__.'/project-model.php';
require_once __DIR__.'/admin-shell.php';
$adminUser=getenv('ADMIN_USERNAME')?:''; $adminPassword=getenv('ADMIN_PASSWORD')?:'';
if($adminUser===''||$adminPassword===''||!hash_equals($adminUser,(string)($_SERVER['PHP_AUTH_USER']??''))||!hash_equals($adminPassword,(string)($_SERVER['PHP_AUTH_PW']??''))) { header('WWW-Authenticate: Basic realm="Grzywniak Discovery"'); http_response_code(401); exit('Authentication required.'); }
header('Content-Type: text/html; charset=utf-8');
$filter=(string)($_GET['filter']??'all');
$allowed=['all','decision','working','client','review','done'];
if(!in_array($filter,$allowed,true))$filter='all';
$search=mb_strtolower(trim((string)($_GET['q']??'')));
$items=[]; $counts=array_fill_keys($allowed,0);
foreach(allSessions() as $session) {
    if(($session['status']??'')!=='COMPLETED' || !empty($session['archivedAt'])) continue;
    $item=projectSnapshot($session);
    $statuses=array_values($item['status']);
    $category=in_array('needs_you',$statuses,true)?'decision':(count(array_intersect(['working','queued'],$statuses))>0?'working':(in_array('waiting_client',$statuses,true)?'client':(in_array('review',$statuses,true)?'review':(end($statuses)==='done'?'done':'all'))));
    $item['category']=$category;
    $counts['all']++; if($category!=='all')$counts[$category]++;
    if($filter!=='all' && $category!==$filter) continue;
    if($search!=='' && !str_contains(mb_strtolower($item['name'].' '.$item['client']),$search)) continue;
    $items[]=$item;
}
usort($items,static fn($a,$b)=>(int)($b['updatedAt']??0)<=>(int)($a['updatedAt']??0));
function h(mixed $value):string{return htmlspecialchars((string)$value,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
$filters=['all'=>'Wszystkie','decision'=>'Moje decyzje','working'=>'Agenci pracują','client'=>'Czeka na klienta','review'=>'Do przeglądu','done'=>'Zakończone'];
ob_start(static fn(string $html):string=>adminShellPage($html,'projects'));
?><!doctype html><html lang="pl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Centrum projektów</title><style>
:root{color-scheme:dark;font-family:Inter,ui-sans-serif,system-ui,sans-serif;background:#080d17;color:#ecf3ff}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 75% -20%,#203b73,transparent 36%),#080d17;min-height:100vh}a{color:inherit;text-decoration:none}main{max-width:1380px;margin:auto;padding:30px 27px 80px}header{display:flex;justify-content:space-between;align-items:center;gap:18px;margin-bottom:34px}.brand{font-size:12px;letter-spacing:.17em;text-transform:uppercase;color:#8ea9d6;font-weight:800}.back{border:1px solid #384c6d;border-radius:9px;padding:9px 13px;font-size:12px;background:#162138}h1{font-size:36px;letter-spacing:-.045em;margin:0 0 8px}.lead{color:#9dafcc;margin:0 0 28px}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:25px}.stat{border:1px solid #2b3f5f;border-radius:15px;background:#111e33;padding:17px}.stat b{font-size:26px;display:block}.stat span{color:#9dafcc;font-size:12px}.filters{display:flex;gap:7px;flex-wrap:wrap;margin-bottom:18px}.filter{border:1px solid #304562;border-radius:999px;padding:8px 13px;background:#111c2e;color:#b8c9e3;font-size:12px}.filter.active{background:#334c8d;color:#fff;border-color:#7897ed}.search{display:flex;margin:0 0 20px}.search input{width:min(420px,100%);border:1px solid #40577a;border-radius:10px;background:#0e192b;color:#e8f1ff;padding:11px 13px;font:inherit}.list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:13px}.item{border:1px solid #2c405d;border-radius:17px;background:linear-gradient(145deg,#14213a,#101928);padding:20px;transition:transform .16s,border-color .16s}.item:hover,.item:focus-visible{transform:translateY(-3px);border-color:#91adf0;outline:0}.item-top{display:flex;justify-content:space-between;gap:12px}.item h2{font-size:18px;letter-spacing:-.025em;margin:0 0 5px}.item small{color:#9cadc9}.pill{border-radius:999px;border:1px solid #536886;color:#c9dafa;font-size:10px;font-weight:800;padding:5px 9px;white-space:nowrap;height:max-content}.pill.decision{border-color:#b88848;color:#ffcd84}.pill.working{border-color:#668ed2;color:#acd1ff}.pill.client{border-color:#9674bc;color:#dbb5ff}.progress{display:flex;gap:3px;margin:19px 0 12px}.progress i{height:5px;flex:1;border-radius:20px;background:#344259}.progress i.done{background:#4ed09d}.progress i.needs_you{background:#eab35a}.progress i.working,.progress i.queued{background:#81aaff}.item-foot{display:flex;justify-content:space-between;gap:10px;color:#90a6c6;font-size:11px}.empty{border:1px dashed #425678;border-radius:16px;padding:50px 20px;text-align:center;color:#a6b9d5}@media(max-width:900px){.cards{grid-template-columns:repeat(2,1fr)}.list{grid-template-columns:1fr}}@media(max-width:560px){main{padding:20px 15px}.item-top{display:block}.pill{display:inline-block;margin-top:10px}.item-foot{display:block}.item-foot span{display:block;margin-top:4px}h1{font-size:28px}}
</style></head><body><main><header><div class="brand">Grzywniak · Centrum projektów</div><a class="back" href="/api/admin.php">← Panel briefów</a></header><h1>Sprawy projektowe</h1><p class="lead">Od przekazanego briefu po wdrożenie. Otwórz sprawę, aby zobaczyć mapę pracy i decyzje.</p><div class="cards"><div class="stat"><b><?=$counts['all']?></b><span>przekazanych briefów</span></div><div class="stat"><b><?=$counts['decision']?></b><span>wymaga Twojej decyzji</span></div><div class="stat"><b><?=$counts['working']?></b><span>zadania w toku</span></div><div class="stat"><b><?=$counts['client']?></b><span>czeka na klienta</span></div></div><nav class="filters" aria-label="Filtr spraw"><?php foreach($filters as $key=>$label):?><a class="filter <?=$filter===$key?'active':''?>" href="?filter=<?=h($key)?><?= $search!==''?'&amp;q='.urlencode($search):'' ?>"><?=h($label)?><?php if($key!=='all'):?> · <?=$counts[$key]?><?php endif?></a><?php endforeach?></nav><form class="search" method="get"><input type="hidden" name="filter" value="<?=h($filter)?>"><input type="search" name="q" value="<?=h($_GET['q']??'')?>" placeholder="Szukaj projektu lub klienta" aria-label="Szukaj projektu lub klienta"></form><div class="list"><?php foreach($items as $item):$state=$item['status'];$active=null;foreach($item['stages'] as $stage)if(in_array($state[$stage['id']]??'',['needs_you','working','queued','ready','error'],true)){$active=$stage;break;}?><a class="item" href="/api/project-case.php?session=<?=h($item['id'])?>"><div class="item-top"><div><h2><?=h(mb_strimwidth($item['name'],0,90,'…'))?></h2><small><?=h($item['client'])?></small></div><span class="pill <?=h($item['category'])?>"><?=h($filters[$item['category']]??'W toku')?></span></div><div class="progress" aria-label="Postęp etapów"><?php foreach($item['stages'] as $stage):?><i class="<?=h($state[$stage['id']]??'locked')?>" title="<?=h($stage['name'].': '.($state[$stage['id']]??'locked'))?>"></i><?php endforeach?></div><div class="item-foot"><span>Następnie: <?=h($active['name']??'Przekazanie')?></span><span>Aktualizacja: <?=date('d.m.Y H:i',(int)($item['updatedAt']??time()))?></span></div></a><?php endforeach?></div><?php if(!$items):?><div class="empty">Brak spraw pasujących do tego filtra.</div><?php endif?></main></body></html>
